/**
  ******************************************************************************
  * @file    cogg_table.h
  * @brief   Anti-cogging feed-forward table for the Trainsonic direct-drive PMSM.
  *
  * Position-indexed Iq feed-forward used to cancel cogging / low-speed torque
  * ripple. Index = mechanical rotor angle (AS5047 14-bit, 0..16383) >> COGG_SHIFT.
  * Values are in s16 current units (same scaling as FOCVars.Iqdref.q).
  *
  * THIS TABLE IS GENERATED -- extracted from board flash by cogg_read.py.
  * Compiling it in makes the calibration survive any reflash, including a full
  * chip erase. Ropetow_CoggInit() loads it first and then lets a valid FLASH map
  * OVERRIDE it, so erase the saved map (console 'n') if you want this one to win.
  *
  * This is a hand-written file (NOT generated by MC Workbench); it survives
  * regeneration. The code that consumes it lives in USER CODE guards.
  ******************************************************************************
  */
#ifndef COGG_TABLE_H
#define COGG_TABLE_H

#include <stdint.h>

/* 16384 mechanical counts / 512 bins = 32 counts/bin = 2^5 -> bin = mech >> 5.
   512 bins resolve mechanical orders up to 256/rev: ample for the felt low-order
   "surge" and moderate cogging, while keeping RAM small. Must stay a power of two
   (the FF lookup wraps with & (COGG_NBINS-1)). */
#define COGG_NBINS  512
#define COGG_SHIFT  5

/* Define COGG_DEFINE_TABLE in exactly ONE translation unit before including this
   header so the const table is instantiated there; everyone else gets the extern. */
#ifdef COGG_DEFINE_TABLE
const int16_t COGG_TABLE_INIT[COGG_NBINS] = {
     128,     82,     31,    -14,    -49,    -69,    -74,    -68,
     -59,    -53,    -56,    -68,    -86,   -104,   -116,   -117,
    -104,    -77,    -40,      4,     52,    100,    140,    168,
     178,    168,    138,     93,     41,     -9,    -48,    -73,
     -83,    -82,    -77,    -73,    -74,    -81,    -91,    -99,
    -101,    -93,    -73,    -43,     -5,     36,     77,    113,
     138,    151,    150,    135,    108,     74,     37,      0,
     -31,    -57,    -76,    -87,    -92,    -94,    -94,    -93,
     -91,    -88,    -79,    -62,    -35,      1,     44,     86,
     120,    139,    141,    127,    103,     76,     53,     39,
      33,     31,     29,     19,     -1,    -32,    -70,   -107,
    -138,   -154,   -153,   -132,    -95,    -45,      8,     60,
     103,    133,    149,    150,    139,    118,     92,     63,
      33,      5,    -18,    -36,    -46,    -51,    -53,    -56,
     -66,    -83,   -106,   -127,   -139,   -132,   -103,    -53,
      11,     78,    137,    176,    192,    184,    158,    120,
      78,     36,      0,    -31,    -52,    -65,    -69,    -66,
     -60,    -56,    -58,    -67,    -83,   -100,   -111,   -109,
     -91,    -55,     -8,     45,     96,    139,    167,    178,
     171,    149,    113,     69,     22,    -20,    -55,    -78,
     -87,    -86,    -81,    -75,    -75,    -81,    -90,    -97,
     -97,    -86,    -60,    -24,     19,     63,    103,    133,
     151,    155,    147,    126,     95,     58,     20,    -16,
     -46,    -68,    -81,    -88,    -92,    -95,    -99,   -102,
    -102,    -96,    -81,    -57,    -25,     11,     48,     82,
     108,    125,    132,    129,    116,     95,     67,     36,
       6,    -21,    -41,    -56,    -65,    -74,    -85,    -99,
    -117,   -132,   -139,   -131,   -105,    -62,     -8,     48,
      99,    136,    155,    157,    144,    122,     94,     63,
      33,      6,    -16,    -32,    -42,    -46,    -48,    -50,
     -57,    -72,    -93,   -116,   -133,   -137,   -122,    -86,
     -35,     24,     84,    133,    165,    177,    168,    143,
     105,     61,     17,    -21,    -50,    -67,    -72,    -68,
     -60,    -54,    -54,    -63,    -79,    -97,   -111,   -115,
    -104,    -77,    -37,     11,     63,    112,    151,    176,
     184,    172,    143,    100,     50,      1,    -40,    -68,
     -81,    -82,    -76,    -69,    -66,    -71,    -80,    -89,
     -92,    -84,    -65,    -34,      3,     43,     80,    111,
     134,    147,    149,    139,    118,     86,     48,      9,
     -25,    -52,    -69,    -77,    -80,    -82,    -86,    -93,
     -98,    -99,    -89,    -68,    -37,      1,     40,     75,
     103,    122,    132,    133,    126,    110,     86,     56,
      24,     -4,    -28,    -43,    -52,    -59,    -69,    -84,
    -104,   -124,   -137,   -134,   -111,    -69,    -15,     40,
      90,    125,    144,    146,    136,    117,     93,     66,
      38,     11,    -11,    -27,    -36,    -38,    -38,    -39,
     -48,    -66,    -91,   -116,   -134,   -137,   -121,    -86,
     -36,     20,     78,    127,    163,    181,    179,    158,
     121,     75,     26,    -15,    -45,    -60,    -60,    -52,
     -44,    -41,    -48,    -63,    -84,   -102,   -113,   -112,
     -98,    -72,    -36,      5,     50,     95,    134,    164,
     176,    169,    141,     97,     46,     -3,    -43,    -66,
     -74,    -71,    -65,    -62,    -66,    -76,    -89,   -100,
    -102,    -93,    -73,    -43,     -9,     27,     63,     95,
     120,    137,    142,    135,    114,     82,     44,      4,
     -31,    -58,    -76,    -86,    -91,    -94,    -98,   -102,
    -105,   -103,    -93,    -74,    -47,    -12,     24,     60,
      90,    113,    126,    129,    122,    106,     82,     53,
      23,     -3,    -24,    -39,    -49,    -59,    -71,    -88,
    -108,   -128,   -140,   -138,   -117,    -79,    -28,     25,
      75,    113,    137,    145,    140,    126,    105,     78,
      49,     21,     -4,    -23,    -35,    -40,    -41,    -43,
     -53,    -71,    -95,   -121,   -141,   -145,   -131,    -96,
     -47,     11,     70,    122,    160,    180,    181,    163,
};
#else
extern const int16_t COGG_TABLE_INIT[COGG_NBINS];
#endif

#endif /* COGG_TABLE_H */
