/**
  ******************************************************************************
  * @file    cogg_table.h
  * @brief   Anti-cogging feed-forward table for the Ropetow direct-drive PMSM.
  *
  * Position-indexed Iq feed-forward used to cancel cogging / low-speed torque
  * ripple. Index = mechanical rotor angle (AS5047 14-bit, 0..16383) >> COGG_SHIFT.
  * Values are in s16 current units (same scaling as FOCVars.Iqdref.q).
  *
  * The default table below is all-zeros (no compensation). It is REGENERATED by
  * the host tool `cogging.py` from a both-direction slow-sweep calibration
  * capture, then compiled in and flashed. Runtime enable/clamp let you A/B test
  * the compiled table without reflashing (CDC 'K'/'k' and 'C<n>').
  *
  * This is a hand-written file (NOT generated by MC Workbench); it survives
  * regeneration. The code that consumes it lives in USER CODE guards.
  ******************************************************************************
  */
#ifndef COGG_TABLE_H
#define COGG_TABLE_H

#include <stdint.h>

/* 16384 mechanical counts / 512 bins = 32 counts/bin = 2^5 -> bin = mech >> 5.
   512 bins resolve mechanical orders up to 256/rev: ample for the felt low-order
   "surge" and moderate cogging, while keeping RAM small. Must stay a power of two
   (the FF lookup wraps with & (COGG_NBINS-1)). */
#define COGG_NBINS  512
#define COGG_SHIFT  5

/* Define COGG_DEFINE_TABLE in exactly ONE translation unit before including this
   header so the const table is instantiated there; everyone else gets the extern. */
#ifdef COGG_DEFINE_TABLE
const int16_t COGG_TABLE_INIT[COGG_NBINS] = {0};   /* host-regenerated; 0 = no comp */
#else
extern const int16_t COGG_TABLE_INIT[COGG_NBINS];
#endif

#endif /* COGG_TABLE_H */
